name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Pint & Rector
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.3]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: "Check PR title"
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: "Install Composer Dependencies"
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: "Run Rector"
        run: |
          ./vendor/bin/rector process --dry-run --config=rector.php

      - name: "Run Pint"
        run: |
          ./vendor/bin/pint --config=pint.json --test --verbose --dirty
